### ISSUE TITLE
perf deg issue 2

### ISSUE THREAD

**Issue by cloudguy2014** [tans-org/test-repo#13]
perf deg issue 2

**Comment by simplyjoe13** [comment]
hey  take a look at it since you know this better.

**Comment by simplyjoe13** [comment]
@simplyjohnny can you take a look at it.

**Comment by simplyjohnny** [comment]
@tans-org/explorer-team  I will start on it next week

**Comment by simplyjohnny** [comment]
not team mention - I will take a look at it next week.

**Comment by simplyjohnny** [comment]
@tans-org/explorer-team  Resending: I will start it on it now.

**Comment by simplyjohnny** [comment]
@cloudguy2014 can you take a look at it.
